### PR TITLE
Fix formula and default vertical cell alignment

### PR DESCRIPTION
**Pull request by Fa-b**
For me, adding even very simple formulas to cells would have Excel fail reading the output.
I encountered the required calcChain schema was missing so I added it.

I tried my best at following your coding style.

I also removed the `=` for formulas in the README since thats not how it should be from my understanding.

Additionally I found that excel defaults to bottom when nothing is explicitly  specified, so I changed that too.

### CODE REVIEW

**Comment by protobi-pieter** [comment]
@Fa-b  This is awesome. Is there a chance you could (a) make the changes to `/src/msexcel-builder.coffee` rather than `lib/msexcel-builder.js` which is autogenerated whenever the former is changed, and (b) update `/test/formula.js`?  If not i can backtrack that from the .js file and your note.

**Comment by Fa-b** [comment]
coffeescript noob here.
To be entirely honest with you, I feel like coffeescript makes it unnecessarily painful to maintain.
I adopted your version of coffeescript and added it as a project dependency so revision history remains readable.
I would suggest to add a contribution note README at some point.
From project root:
```
coffee --map -o lib/ -c src/
```

At some point though, I would review if coffeescript can be updated to a more recent version (or drop it alltogether 😜).

- ~~Give me some time to check if the generated output does it's job well (I have to traverse changes through my other branches to verify).~~

- ~~And then add tests.~~

- ~~I also found a copy paste bug in one of your previous merges (see comment [here](https://github.com/protobi/msexcel-builder/commit/c5e24401ccd678b3d5e52379db6e45756d3a8edd#r57653936)) that I would like to address in this PR if you don't mind.~~

~~This PR is not yet finished~~

**Comment by Fa-b** [comment]
Alright @pietersv this should be it!

There are other tests that fail though. Should be unrelated to my changes.

**Review by protobi-pieter — APPROVED** [review]

**Comment by protobi-pieter** [comment]
I see many of the tests write files to directories that are assumed but not guaranteed to exist, and will fix that.

**Pull request merged**
