### PR TITLE
Fixed number formats

### LINKED ISSUE #10: Number Format Issue
I'm currently having an issue when setting number formats in different cells.
The number format does not show when I open the exported file in Excel. Here is the code I use to set a specific cell's number format. 
```
{
fill : { type: "solid", fgColor: "00FFFFFF", bgColor: "-" },
font : { name: "Calibri", sz: 8 },
numberFormat: "0.00",
set:0.5524822392015282,
}
```

For some reason, the numberFormat property works when I set ALL of the cells to use the same numberFormat (ex: '0.00').

### LINKED ISSUE #14: Currency Format Not Supported
I want to format a cell as currency: `'$#,###.00'`, but when I do this I get the error:

```
msexcel-builder.js:629 Uncaught Number format $#,###.00 not found.  Custom number formats not implemented yet
```

Is there any way I can render a number as currency?

### PR DESCRIPTION
**Pull request by JonnoFTW**
Fixes #14 
Fixes #10 
Fixes PR #9 

Feel free to review the code and do whatever tests you need

### CODE REVIEW

**Comment by protobi-pieter** [comment]
Wow, if this came 10 minutes later I would have thought a message declaring a this many issues getting fixed with unit tests to boot was an April fools prank

**Comment by JonnoFTW** [comment]
@pietersv any update on this getting merged?

**Comment by protobi-pieter** [comment]
@JonnoFTW  Thanks for the updates! I definitely intend to test and merge these changes.  Merging changes is taking on responsibility for future issues, so I just need to be methodical about it and am crunched for time this week.  Since you've got your branch, my assumption was that is good enough to include in your work, but if dependent on this being in npm  can look to accelerate that.  -- Piet

**Comment by JonnoFTW** [comment]
Fair enough,  I've switch the version over in my project to use my version for the time being.

**Review by protobi-pieter — APPROVED** [review]

**Pull request merged**
